Repository Henriknn01/ShopFrontend, pull requests merged in 2023-05, with the labels that each got.

#29 Product page use carousel improvements
  components/Carousel.vue
  composables/useCarousel.ts
  composables/useChat.ts
  pages/index.vue
  server/api/auth/[...].ts
Labels: development

#21 Feature nav bar
  components/Carousel.vue
  components/ShopHeader.vue
  composables/useNavBar.ts
  package.json
Labels: development

#31 Blog
  composables/useBlog.ts
  pages/blog/[id]/index.vue
  pages/blog/index.vue
Labels: development

#32 Feature category cards
  components/categoryCard.vue
  composables/useCategoryCard.ts
  pages/categories/[id]/index.vue
  pages/index.vue
Labels: development

#33 Feature category cards
  composables/useCategoryCard.ts
Labels: development

#34 Product page
  components/Carousel.vue
  components/Reviews.vue
  components/ShopHeader.vue
  composables/useCarousel.ts
  composables/useChat.ts
  composables/useNavBar.ts
  composables/useReviews.ts
  interfaces/ICartItem.ts
  interfaces/ICartState.ts
  interfaces/ILineItem.ts
  nuxt.config.ts
  pages/cart/index.vue
  pages/categories/index.vue
  pages/index.vue
  pages/product/[id].vue
  pages/product/[id]/index.vue
  pages/product/index.vue
  server/api/chat.ts
  server/api/user/activate.ts
  server/api/user/reset.ts
  stores/ShoppingCart.ts
Labels: development

#36 added back categories to nav bar
  components/ShopHeader.vue
Labels: development

#37 added clickable carousel items
  components/Carousel.vue
  composables/useCarousel.ts
Labels: development

#38 Categories
  components/Carousel.vue
  components/categoryCard.vue
  pages/categories/[id]/index.vue
  pages/index.vue
  pages/product/[id].vue
Labels: bug, development

#40 Carousel patch
  components/Carousel.vue
  composables/useCarousel.ts
Labels: development

#42 moved everything into components
  components/Carousel.vue
  composables/useCarousel.ts
  pages/index.vue
Labels: development

#43 Categorycard patch
  components/categoryCard.vue
Labels: development

#44 added category parrent check
  components/categoryCard.vue
Labels: development

#46 removed double merge error
  components/Carousel.vue
Labels: development

#47 Categorycard patch
  components/categoryCard.vue
Labels: development

#48 Patch navbar
  components/ShopHeader.vue
  composables/useNavBar.ts
Labels: development

#49 small patch
  components/ShopHeader.vue
Labels: development

#52 needed changing to sort items
  components/ShopHeader.vue
Labels: development

#53 Finished checkout integration with stripe and the backend
  composables/useAuthFetch.ts
  interfaces/ICartState.ts
  pages/cart/checkout/success.vue
  server/api/checkout/expire.post.ts
  server/api/checkout/retrieve/[id].ts
  stores/ShoppingCart.ts
Labels: development

#54 Productlist page
  pages/categories/[id]/index.vue
  pages/productlist/[id].vue
Labels: development

#55 Create user
  components/ShopHeader.vue
  composables/useAuthExtention.ts
  layouts/login.vue
  nuxt.config.ts
  pages/about.vue
  pages/account/create.vue
  pages/account/login.vue
  pages/blog/[id]/index.vue
  pages/blog/index.vue
  pages/cart/index.vue
  pages/categories/[id]/index.vue
  pages/categories/index.vue
  pages/index.vue
  pages/login.vue
  pages/product/[id].vue
  pages/productlist/[id].vue
  server/api/auth/[...].ts
  stores/ShoppingCart.ts
Labels: development

#58 added blog posts to product page
  composables/useBlog.ts
  pages/product/[id].vue
Labels: development

#57 added privacy.vue, added qanda.vue, tos.vue, changed headers and foot…
  components/ShopFooter.vue
  components/ShopHeader.vue
  pages/blog/index.vue
  pages/privacy.vue
  pages/qanda.vue
  pages/tos.vue
Labels: development

#56 Accessable button patch
  components/Carousel.vue
  components/ChatBox.vue
  nuxt.config.ts
  pages/index.vue
  pages/product/[id].vue
Labels: development

#60 Update ShopFooter.vue
  components/ShopFooter.vue
Labels: development

#62 Remove signout from header
  components/ShopHeader.vue
  pages/account/index.vue
Labels: bug

#64 fix for build issues
  nuxt.config.ts
  package.json
  pages/product/[id].vue
  yarn.lock
Labels: bug

#69 Update index.vue
  pages/index.vue
Labels: development

#73 fixed blog posts | fixed about page
  composables/useBlog.ts
  pages/about.vue
  pages/blog/[id]/index.vue
Labels: bug, development

#75 Testimonial
  pages/about.vue
  pages/index.vue
Labels: development

#79 added link to ToS in create account page
  pages/account/create.vue
Labels: development

#78 Added sprint report
  Documents/Sprint Report Frontend.docx
Labels: development

#77 added accessibility fixes for productlist and reviewform
  components/ReviewForm.vue
  pages/productlist/[id].vue
Labels: bug, development

#80 Documentation
  Documents/infrastructure.png
  README.md
Labels: documentation, development
